http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  signupapi:
    host: '*'
    paths:
      - '/signup'
      - '/signup/createaccount'
      - '/signup/*'
  loginapi:
    host: '*'
    paths:
      - '/signin'
      - '/signin/*'
serviceEndpoints:
  signupservice:
    url: ${SIGNUP_URL:-'http://localhost:3000/'}
  loginservice:
    url: ${LOGIN_URL:-'http://localhost:50000/'}
policies:
  # - basic-auth
  # - cors
  # - expression
  # - key-auth
  # - log
  # - oauth2
  - proxy
  # - rate-limit
pipelines:
  pipeline1:
    apiEndpoints:
      - signupapi
    policies:
      - proxy:
          - action:
              serviceEndpoint: signupservice
              changeOrigin: true
  pipeline2:
    apiEndpoints:
      - loginapi
    policies:
      - proxy:
          - action:
              serviceEndpoint: loginservice
              changeOrigin: true
